export const NEW_POST = "NEW_POST";
export const LOCATION_CHANGE = "LOCATION_CHANGE";
export const CHANGE_FORM_STATE = 'CHANGE_FORM_STATE';
export const ACTIVATE_IDEA = 'ACTIVATE_IDEA';
export const CHANGE_PRIORITY = 'CHANGE_PRIORITY';
export const CHANGE_IS_DRAG = 'CHANGE_IS_DRAG';
export const CHANGE_DRAGGING_ITEM = 'CHANGE_DRAGGING_ITEM';
